-- study_sqls DB 생성
-- Tables 생성
-- 공유한 엑셀 값들 데이터로 입력
-- + 회원 가입 모두(U1 ~ U4)
-- + 회원 탈퇴(U2, U4)
INSERT INTO auth_names(AUTH_NAME, UNIQUE_ID)
VALUES ('GUEST', 'B1') 
;
INSERT INTO auth_names(AUTH_NAME, UNIQUE_ID)
VALUES ('ADMIN', 'B2')
;
INSERT INTO auth_names(AUTH_NAME, UNIQUE_ID)
VALUES ('MANAGER', 'B3')
;

INSERT INTO users (UNIQUE_ID, NAME, EMAIL, JOB)
VALUES ('U1', 'Paul', 'paul01@gmail.com',' IT Billing');

INSERT INTO users (UNIQUE_ID, NAME, EMAIL, JOB)
VALUES ('U2', 'Allen', ' texas@imfblog.org',' Engineering');

INSERT INTO users (UNIQUE_ID, NAME, EMAIL, JOB)
VALUES ('U3', 'Teddy', ' norway@iotm.com',' IT Billing’');

INSERT INTO users (UNIQUE_ID, NAME, EMAIL, JOB)
VALUES ('U4', 'Paul', 'paul_p@naver.com',' Developer');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U1', 'B1');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U1', 'B2');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U2', 'B1');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U2', 'B2');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U2', 'B3');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U3', 'B1');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U4', 'B2');

INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U4', 'B1');

DELETE FROM auths
WHERE UNIQUE_ID_USERS in ('U2');

DELETE FROM auths
WHERE UNIQUE_ID_USERS in ('U4');

DELETE FROM users
WHERE UNIQUE_ID in ('U2');

DELETE FROM users
WHERE UNIQUE_ID in ('U4');

SELECT *
FROM users;

SELECT *
FROM auths;